### ISSUE TITLE
Dockerfile currently not usable

### ISSUE THREAD

**Issue by legionth** [sdelements/lets-chat#393] opened 2015-04-08 08:46 UTC
I tried to use Let's chat with the dockerfile.

But when I tried to create a chatroom I got following error:
<pre>
Release 0.3.9

/usr/src/app/node_modules/cookie-parser/node_modules/cookie-signature/index.js:38
  if ('string' != typeof secret) throw new TypeError("Secret string must be pr
                                       ^
TypeError: Secret string must be provided.
    at Object.exports.unsign (/usr/src/app/node_modules/cookie-parser/node_modules/cookie-signature/index.js:38:40)
    at Object.exports.signedCookie (/usr/src/app/node_modules/cookie-parser/lib/parse.js:45:17)
    at Object.exports.signedCookies (/usr/src/app/node_modules/cookie-parser/lib/parse.js:23:19)
    at cookieParser (/usr/src/app/node_modules/cookie-parser/index.js:41:33)
    at getSession (/usr/src/app/node_modules/express.oi/lib/session.js:32:5)
    at Array.handleSession [as 0] (/usr/src/app/node_modules/express.oi/lib/session.js:54:5)
    at run (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:114:11)
    at Namespace.run (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:126:3)
    at Namespace.add (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:155:8)
    at Client.connect (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/client.js:74:20)

npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.9 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the lets-chat@0.3.9 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
</pre>

**Comment by legionth** [comment] 2015-04-08 08:51
After that it is not even possible to start the docker container.

**Comment by thisgeekza** [comment] 2015-04-08 08:52
After upgrading from 0.3.8, I am getting the same issue. All I changed was the xmpp.host to xmpp.domain in the settings.yml.

**Comment by chiel1980** [comment] 2015-04-08 13:53
I got the same:

1) created the docker container
2) registered a new user via http://ip:5000
3) when I log in with the username I get the same error:

/usr/src/app/node_modules/cookie-parser/node_modules/cookie-signature/index.js:38
  if ('string' != typeof secret) throw new TypeError("Secret string must be pr
                                       ^
TypeError: Secret string must be provided.
    at Object.exports.unsign (/usr/src/app/node_modules/cookie-parser/node_modules/cookie-signature/index.js:38:40)
    at Object.exports.signedCookie (/usr/src/app/node_modules/cookie-parser/lib/parse.js:45:17)
    at Object.exports.signedCookies (/usr/src/app/node_modules/cookie-parser/lib/parse.js:23:19)
    at cookieParser (/usr/src/app/node_modules/cookie-parser/index.js:41:33)
    at getSession (/usr/src/app/node_modules/express.oi/lib/session.js:32:5)
    at Array.handleSession [as 0] (/usr/src/app/node_modules/express.oi/lib/session.js:54:5)
    at run (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:114:11)
    at Namespace.run (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:126:3)
    at Namespace.add (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/namespace.js:155:8)
    at Client.connect (/usr/src/app/node_modules/express.oi/node_modules/socket.io/lib/client.js:74:20)
 
npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE
npm ERR! lets-chat@0.3.9 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the lets-chat@0.3.9 start script 'node app.js'.
npm ERR! This is most likely a problem with the lets-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls lets-chat
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by sibartlett** [comment] 2015-04-08 14:14
I think I know what might be causing the error - one of our dependencies has changed in the past 12 hours.

I should have it fixed soon - I'm currently commuting to the office.

**Comment by chiel1980** [comment] 2015-04-08 14:21
Thanks for the support and help :)

**Comment by sibartlett** [comment] 2015-04-08 15:37
Hey everyone, this is now fixed. If you're using the docker file - you'll need to rebuild the image/container.

The problem was caused by a change in express-session, so for the time-being I have fixed the version we're depending on.

**Closed by sibartlett** 2015-04-08 15:37 UTC

**Comment by chiel1980** [comment] 2015-04-08 16:03
Hi Simon,

How should I update this fix?
I tried the following:

cd /usr/local/lets-chat
git pull
docker rm *image/container* # except mongodb
docker build -t lets-chat .
docker run -p 5000:5000 --link db:db lets-chat

everything seems to be running without errors:
[root@server lets-chat]# netstat -an | grep 5000
tcp        0      0 :::5000                     :::*
 LISTEN

docker logs $dockercontainerid:

> lets-chat@0.3.9 prestart /usr/src/app
> migroose


> lets-chat@0.3.9 start /usr/src/app
> node app.js


██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.3.9

Testing the connection with curl (get actual content)

[root@server lets-chat]# curl localhost:5000
curl: (56) Failure when receiving data from the peer

It seems there is something wrong with this upgrade procedure I tried, do
you know what I did wrong with this upgrade?

Cheers,

Michiel

2015-04-08 17:38 GMT+02:00 Simon Bartlett <notifications@github.com>:

**Comment by thisgeekza** [comment] 2015-04-08 16:37
Thanks, the fix is working for me.

**Comment by legionth** [comment] 2015-04-14 08:28
Thank you it's working now!
