### ISSUE TITLE
Installing Let's Chat at non root path

### ISSUE THREAD

**Issue by eliemichel** [sdelements/lets-chat#208] opened 2015-02-10 22:52 UTC
It would be very usefull to be able to run Let's Chat at, say, example.org/chat.

**Comment by funkaoshi** [comment] 2015-02-11 15:22
@sibartlett we can already do this as part of 0.3.0, correct? This looks to be a duplicate of #78.

**Comment by sibartlett** [comment] 2015-02-11 15:44
We did address this, but then in release 0.3.1 we introduced an [asset pipeline](https://github.com/adunkman/connect-assets) - which outputs absolute paths in the HTML response.

However, if you use nginx or apache to proxy Let's Chat - you can configure them to rewrite the links in the HTML source.

**Comment by eliemichel** [comment] 2015-02-11 16:28
Well, if it is possible, it is not documented in the wiki's configuration documentation. Or at least I did not found it.

And what are you talking about when you say that Apache/nginx can rewrite URLs *inside* HTML?

**Comment by sibartlett** [comment] 2015-02-11 16:32
For Apache, there's a module called [```mod_proxy_html```](http://httpd.apache.org/docs/current/mod/mod_proxy_html.html).

For nginx, there's a module called [HttpSubmodule](http://wiki.nginx.org/HttpSubsModule).

I've used the Apache module a long time ago. I haven't tried the nginx module.

**Comment by LouisKottmann** [comment] 2015-02-13 13:37
This functionality is important to me as well, and since it is uncommon in open source webchats (including web irc clients, and believe me I tried many), you'd have a selling point.

I think an effort spent in restoring non-root hosting would pay off ;)

**Comment by sibartlett** [comment] 2015-02-13 15:18
I'm reopening this issue for now.

**Comment by geoffwhittington** [comment] 2015-02-24 04:02
From the links @sibartlett posted it appears non-root support is achievable using these apache and nginx modules. If this is important to you I suggest that someone try these out and post their results. We will update the wiki with the information.

**Comment by LouisKottmann** [comment] 2015-02-24 12:42
@geoffwhittington the links posted suggest making nginx rewrite every page it proxies through the use of regexps... that's brittle to say the least!

**Comment by geoffwhittington** [comment] 2015-02-25 02:05
Do you mean it's brittle because the solution won't work all the time or because it requires additional processing to rewrite the pages?

I agree it's not an optimal solution, but it appears to be, at least theoretically, a solution. In your use case, has rewriting the pages with one of these options caused a noticeable impact on your server? I'm interested to know, from a project and technical point of view.

**Comment by geoffwhittington** [comment] 2015-02-25 02:15
Nevertheless the issue remains open to be resolved within the code. We don't have an immediate need for this feature but if someone wants to work on it - we can point them in the right direction code-wise.

**Comment by hhaidar** [comment] 2015-02-25 02:18
@LouisKottmann can you recommend a solution that works for you?

**Comment by LouisKottmann** [comment] 2015-02-25 13:59
My solution right now is to use kiwiirc, because it is the only "serious" open source chat project out there that actually supports being hosted at a non-root path.

If I ever need non-technical people to use my chat and decide to turn to letschat, I'll take the time to implement it ;)

**Closed** 2015-02-25 14:18 UTC
Labels: duplicate

**Comment by sibartlett** [comment] 2015-02-25 14:20
@eliemichel @LouisKottmann I've pushed a fix for this - Let's Chat should now on a non-root path.

**Comment by geoffwhittington** [comment] 2015-02-25 14:28
@sibartlett Can you re-check the name of the function you added? There may still be an issue in the code

**Comment by sibartlett** [comment] 2015-02-25 14:35
Woops! Didn't stage my changes properly, now fixed.

**Comment by eliemichel** [comment] 2015-02-27 13:38
@sibartlett Nice! I gonna test it soon.
