### ISSUE TITLE
Add ability to correct errors in previously sent message.

### ISSUE THREAD

**Issue by depinav** [sdelements/lets-chat#305] opened 2015-02-23 15:35 UTC
So in hipchat (which I use for work) theres a feature that you can use s/<error>/<correction> to correct a mistake in the last message you sent. It comes in handy with typos etc.

**Comment by funkaoshi** [comment] 2015-02-23 15:52
Duplicate of #193.

**Closed by funkaoshi** 2015-02-23 15:52 UTC
