### ISSUE TITLE
LDAP plugin not working against develop branch

### ISSUE THREAD

**Issue by louis-gounot** [sdelements/lets-chat#477] opened 2015-06-04 08:21 UTC
There is a dependency conflict regarding mongoose between lets-chat (develop branch) and lets-chat-ldap.
Wanted to use develop branch for private rooms but LDAP integration is mandatory for me.

**Comment by hhaidar** [comment] 2015-06-04 15:15
@louis-gounot are you getting an error or something? Seems to be working fine for me locally.

**Comment by louis-gounot** [comment] 2015-06-04 15:40
Here is what I'm doing : 
```bash
git clone https://github.com/sdelements/lets-chat.git
cd lets-chat
git checkout develop
npm install
npm install lets-chat-ldap
```
This leads to : 
```
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer lets-chat-ldap@0.4.0 wants mongoose@~3.8.22

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "lets-chat-ldap"
npm ERR! cwd /home/login/letschat/lets-chat-develop
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/login/letschat/lets-chat-develop/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sibartlett** [comment] 2015-06-04 15:41
I'll fix this today.

**Comment by louis-gounot** [comment] 2015-06-04 15:45
Thanks a lot :+1:

**Comment by sibartlett** [comment] 2015-06-04 16:32
@louis-gounot this should now be fixed. Please try reinstalling the plugin.

**Comment by louis-gounot** [comment] 2015-06-05 08:39
@sibartlett Install is OK now. But I can't start the app, stucked in migroose phase.

**Comment by sibartlett** [comment] 2015-06-05 13:08
@louis-gounot are you using the latest code from master? I made a fix for the migroose problem.

**Comment by louis-gounot** [comment] 2015-06-05 14:38
@sibartlett I just tested with master branch. I can install (with ldap extension) and start the app.
Fresh blank mongo database is correctly populated. (so previously reported issues are OK now).
The new issue : the app crash when I try to create a private room :
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by louis-gounot** [comment] 2015-06-05 14:40
@sibartlett : in order to clarify, here is what I try to achieve : 
Use let's chat with ability to : 
  - login through LDAP 
  - be able to create private rooms where participants can chat only if they have been added to participant list.

**Comment by hailkomputer** [comment] 2015-06-17 09:43
@louis-gounot 
I am having the same issue as yours at the moment, were you able to find a solution/fix regarding this?

**Comment by sibartlett** [comment] 2015-06-17 11:28
@hailkomputer I assume you're using the latest version?

**Comment by hailkomputer** [comment] 2015-06-17 12:09
@sibartlett 
Yes, it is the latest version.

**Comment by louis-gounot** [comment] 2015-06-22 15:36
Hello,

@sibartlett, @hailkomputer It is working now for me.
I'm using commit db2162bae91f330703049689bc74e7049ca14cf3 (Jun 15) for lets-chat with lets-chat-ldap v0.5 from NPM.
I've set rooms/private setting to true and disabled private rooms (was confusing, private setting s allow for 1to1 chats, rooms/private allows what I was looking for).

Install procedure exactly the same than the one dexscribed in one of my previous messages in this issue.

**Comment by hailkomputer** [comment] 2015-06-22 16:24
@sibartlett @louis-gounot 

Hello thank you for your answers, I've attempted a clean install to new VM and now it is working properly. It was probably caused by a misconfiguration on my behalf.

**Comment by sibartlett** [comment] 2015-06-22 17:59
@louis-gounot @hailkomputer thanks for the updates! I'll close this ticket as it seems al issues have been resolved. If you have further issues, please open new issues!

@louis-gounot we'll update the documentation soon to clarify the new configuration settings. Thanks!

**Closed by sibartlett** 2015-06-22 17:59 UTC
