### ISSUE TITLE
Do you plan to add test to this sweet thing?

### ISSUE THREAD

**Issue by zzz6519003** [sdelements/lets-chat#394] opened 2015-04-08 16:00 UTC

**Comment by geoffwhittington** [comment] 2015-04-08 16:02
This is a duplicate of #185 

Do you experience writing tests? We'd love to have you contribute!

**Closed by geoffwhittington** 2015-04-08 16:02 UTC

**Comment by zzz6519003** [comment] 2015-04-08 16:12
i'm sorry i haven't have read that!

**Comment by geoffwhittington** [comment] 2015-04-08 16:14
No worries. Do you want to help write tests?

**Comment by hhaidar** [comment] 2015-04-08 16:25
![image](https://cloud.githubusercontent.com/assets/1066160/7049770/58bc85ac-ddea-11e4-9348-ba210709d11d.png)

**Comment by geoffwhittington** [comment] 2015-04-08 16:30
I can't quite make out all the features on that picture @hhaidar  But the tears! I see them

**Comment by zzz6519003** [comment] 2015-04-24 15:31
i love test! but i think it may be difficult for me to get startedT.T
