### ISSUE TITLE
Mobile Web App for Let's Chat (android/ios)

### ISSUE THREAD

**Issue by JohnTheodore** [sdelements/lets-chat#410] opened 2015-04-16 06:53 UTC
So if I could use let's chat on my phone, that would be epic. No native code, just a wrapper around webkit. Very similar to how slack does it.

**Comment by tonghuix** [comment] 2015-04-16 07:45
Hi, it could run in your phone via any browser, please have a try for that

**Comment by geoffwhittington** [comment] 2015-05-08 03:40
@JohnTheodore Lets Chat is responsive to a mobile interface. Check it out!

If this is a request for a type of phonegap-style app this is a duplicate of #216

**Closed by geoffwhittington** 2015-05-08 03:40 UTC
