### ISSUE TITLE
File upload in room

### ISSUE THREAD

**Issue by martin-gobert-dev** [sdelements/lets-chat#684] opened 2016-03-02 13:24 UTC
Hello,
I have installed lets-chat on my dedicated server.
First, thank you for your jobs, the chat is great.

I just have a little trouble.
For lot of reasons, I put the chat behind a apache2 http_proxy.
So the base url of the chat is https://url.ext/chat
When I upload files, in the right sections, I can see the file.
But on the center section where chat messages are, I can not see my file.

The reason is, the link to my file is : https://url.ext/files and should be https://url.ext/chat/files (like in the right section).
I also have anothers proxys on this VirtualHost, and /files is proxying to another web server (a file manager).

How could I correct the problem ?

I am not afraid to see & change the code, I just dont know NodeJS, I am PHP man :p

Thank you for your work!

**Comment by alexdorn87** [comment] 2016-07-08 09:00
The problem is fixed by #699.

**Comment by hhaidar** [comment] 2016-07-08 17:01
thanks @alexdorn87

**Closed by hhaidar** 2016-07-08 17:01 UTC
